#!/usr/bin/env bash
# Link vendor-specific agent config directories at .agents/, the single source
# of truth for agent instructions, skills and hooks.
#
# Codex reads $REPO_ROOT/.agents/skills natively — no link needed there.
# Claude Code discovers skills under .claude/skills and subagents under
# .claude/agents, so those paths are symlinks into .agents/. Subagents have no
# Codex equivalent; they are shared-tree for ownership, not for portability.
# Links are gitignored and regenerated by this script, so
# a Windows clone without symlink support is never left with broken entries in
# the working tree.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# target -> link path, relative to the repo root.
link() {
    local target="$1" link_path="$2"
    local link_dir link_rel
    link_dir="$(dirname "$link_path")"

    if [ ! -e "$target" ]; then
        echo "skip  $link_path (no $target)"
        return
    fi

    # A real directory here would be a pre-migration leftover; refuse rather
    # than delete files the script did not create.
    if [ -d "$link_path" ] && [ ! -L "$link_path" ]; then
        echo "ERROR $link_path is a real directory, not a link." >&2
        echo "      Move its contents into $target and remove it, then re-run." >&2
        exit 1
    fi

    mkdir -p "$link_dir"
    # Relative target so the link survives clones at any absolute path.
    link_rel="$(realpath --relative-to="$link_dir" "$target")"
    ln -sfn "$link_rel" "$link_path"
    echo "link  $link_path -> $link_rel"
}

link .agents/skills .claude/skills
link .agents/agents .claude/agents

echo
echo "Agent config linked. Codex reads .agents/skills and AGENTS.md directly."
